services:
  discord_bot:
    build:
      context: /mnt/disk1/appdata/wsbd-icy/
      dockerfile: Dockerfile
    container_name: wsbd-icy
    environment:
      - DISCORD_TOKEN= # Replace with your token
    volumes:
      - /mnt/disk1/appdata/wsbd-icy/:/app/  # Map assets folder to app container direclty to disk user for faster reads and writes (in unraid at least)
    env_file:
      - /mnt/disk1/appdata/wsbd-icy/.env
    network_mode: "" # Replace with your network
    restart: unless-stopped